- hosts: all
  become: true
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
        upgrade: dist

    - name: Update all packages to their latest version
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - ufw
        state: present
        update_cache: true

    - name: Allow SSH through firewall
      ufw:
        rule: allow
        port: "22"
        proto: tcp

    - name: Allow HTTP(S) through firewall
      ufw:
        rule: allow
        port: "80,443"
        proto: tcp

    - name: Enable firewall
      ufw:
        state: enabled
        policy: deny
