# Deploy latest image

- import_playbook: playbooks/install-base.yml
- import_playbook: playbooks/install-docker.yml
- import_playbook: playbooks/install-webserver.yml
- import_playbook: playbooks/pull-image.yml
